-- V1 leave rules from the founder's policy, in force from January 2026. Mirrors src/modules/rules/v1.ts
-- (V1_LEAVE_RULE_ROWS); tests/db/leave.test.ts fails if the two ever differ.
-- Maternity, paternity, bereavement and family emergency are provisional pending the legal minimums.
insert into public.rules (key, employment_type, effective_from, value, note) values
  ('leave_policy', 'full_time', '2026-01-01', '{"types":{"annual":{"allowance":{"kind":"per_year","days":25,"prorate":true},"count":"working","half_days":true,"paid":true},"sick":{"allowance":{"kind":"per_year","days":14,"prorate":true},"count":"working","half_days":true,"paid":true},"professional_development":{"allowance":{"kind":"per_year","days":5,"prorate":true},"count":"working","half_days":true,"paid":true},"maternity":{"allowance":{"kind":"per_event","days":180,"later_child_days":90,"within_days_of_event":null},"count":"calendar","half_days":false,"paid":true},"paternity":{"allowance":{"kind":"per_event","days":10,"later_child_days":5,"within_days_of_event":30},"count":"working","half_days":false,"paid":true},"bereavement":{"allowance":{"kind":"per_event","days":7,"later_child_days":null,"within_days_of_event":null},"count":"working","half_days":true,"paid":true},"family_emergency":{"allowance":{"kind":"per_year","days":3,"prorate":false},"count":"working","half_days":true,"paid":true},"unpaid":{"allowance":{"kind":"unlimited"},"count":"working","half_days":true,"paid":false}}}'::jsonb, 'V1 leave policy. Special leave values provisional pending the legal minimums'),
  ('leave_carry_forward', 'full_time', '2026-01-01', '{"days":{"annual":0,"sick":0,"professional_development":0,"family_emergency":0}}'::jsonb, 'No carry-forward in V1'),
  ('working_week', 'full_time', '2026-01-01', '{"days":[1,2,3,4,5]}'::jsonb, 'Monday to Friday'),
  ('proration_cutoff', 'full_time', '2026-01-01', '{"day":15}'::jsonb, 'Joining month counts on or before the 15th; exit month on or after it'),
  ('leave_backdate', 'full_time', '2026-01-01', '{"months":1}'::jsonb, 'Requests may go back to the start of last month'),
  ('leave_exit_payout', 'full_time', '2026-01-01', '{"enabled":false}'::jsonb, 'Unused annual leave is not paid out on exit'),
  ('leave_policy', 'intern', '2026-01-01', '{"types":{"sick":{"allowance":{"kind":"per_year","days":14,"prorate":true},"count":"working","half_days":true,"paid":true},"maternity":{"allowance":{"kind":"approval_only"},"count":"calendar","half_days":false,"paid":true},"paternity":{"allowance":{"kind":"approval_only"},"count":"working","half_days":false,"paid":true},"bereavement":{"allowance":{"kind":"approval_only"},"count":"working","half_days":true,"paid":true},"family_emergency":{"allowance":{"kind":"approval_only"},"count":"working","half_days":true,"paid":true},"unpaid":{"allowance":{"kind":"unlimited"},"count":"working","half_days":true,"paid":false}}}'::jsonb, 'V1 leave policy. Special leave values provisional pending the legal minimums'),
  ('leave_carry_forward', 'intern', '2026-01-01', '{"days":{"annual":0,"sick":0,"professional_development":0,"family_emergency":0}}'::jsonb, 'No carry-forward in V1'),
  ('working_week', 'intern', '2026-01-01', '{"days":[1,2,3,4,5]}'::jsonb, 'Monday to Friday'),
  ('proration_cutoff', 'intern', '2026-01-01', '{"day":15}'::jsonb, 'Joining month counts on or before the 15th; exit month on or after it'),
  ('leave_backdate', 'intern', '2026-01-01', '{"months":1}'::jsonb, 'Requests may go back to the start of last month'),
  ('leave_exit_payout', 'intern', '2026-01-01', '{"enabled":false}'::jsonb, 'Unused annual leave is not paid out on exit');
